version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - elder-studio-network

  admin-engine:
    build:
      context: ./admin-frontend
      args:
        NEXT_PUBLIC_API_URL: http://staff.elderworldsstudio.com
    container_name: admin-engine
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://staff.elderworldsstudio.com
    depends_on:
      - backend
    networks:
      - elder-studio-network

  omnivael-reader:
    build:
      context: ./omnivael-frontend
      args:
        NEXT_PUBLIC_API_URL: http://omnivael.com
    container_name: omnivael-reader
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://omnivael.com
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://omnivael.com
    depends_on:
      - backend
    networks:
      - elder-studio-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - admin-engine
      - omnivael-reader
    networks:
      - elder-studio-network

networks:
  elder-studio-network:
    driver: bridge
